#pragma once
/*
//	DefineMotionLoopTime.h
//
//	(C) Power. 2020 ~
*/
#define WAIT_IDLE_READTIME					TIME1MS
#define WAIT_POSITIONSET_READTIME			TIME1MS
#define WAIT_DELAYEDPOSITIONSET_READTIME	TIME1MS
#define WAIT_MOTION_READTIME				TIME1MS
#define WAIT_REMOVE_ARRAY_WAITTIME			TIME1MS
#define WAIT_SERVOON_WAITTIME				TIME100MS
#define WAIT_SERVOOFF_WAITTIME				TIME10MS

