//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// PowerCalibration.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FORM_HOME                   101
#define IDD_POWERCALIBRATION_DIALOG     102
#define IDD_FORM_MAIN                   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_FORM_CAMCAL                 103
#define IDD_FORM_MASTER                 104
#define IDR_MAINFRAME                   128
#define IDI_POWER                       144
#define IDC_LIST_SEND                   1000
#define IDC_LIST_RECV                   1001
#define IDC_EDIT_SEND                   1002
#define IDC_BTN_SEND                    1003
#define IDC_RADIO_HOME                  1011
#define IDC_STATIC_RECT                 1012
#define IDC_RADIO_CAMCAL                1013
#define IDC_RADIO_SOCKET                1014
#define IDC_BTN_STOPSEND                1015
#define IDC_EDIT_AXIS1_NO               1016
#define IDC_BTN_READ                    1017
#define IDC_EDIT_AXIS2_NO               1018
#define IDC_EDIT_AXIS1_MODE             1019
#define IDC_EDIT_AXIS2_MODE             1020
#define IDC_EDIT_AXIS1_ONOFF            1021
#define IDC_EDIT_AXIS2_ONOFF            1022
#define IDC_EDIT_AXIS1_HOME             1023
#define IDC_EDIT_TORQUE_Y               1024
#define IDC_EDIT_AXIS2_HOME             1025
#define IDC_LISTBOX_LOG                 1026
#define IDC_BTN_AXIS1_SERVO             1027
#define IDC_BTN_AXIS2_SERVO             1028
#define IDC_RADIO_MASTER                1029
#define IDC_EDIT_LIBVERSION             1030
#define IDC_EDIT_IMDLLVERSION           1031
#define IDC_EDIT_VALID                  1032
#define IDC_EDIT_ONSLAVECOUNT           1033
#define IDC_EDIT_OFFSLAVECOUNT          1034
#define IDC_EDIT_REF_FEEDERNO           1035
#define IDC_EDIT_FD_NO                  1036
#define IDC_EDIT_HEIGHT                 1037
#define IDC_EDIT_STOPPER_UP             1038
#define IDC_EDIT_INACCESSCOUNT          1039
#define IDC_EDIT_FEEDER_PITCH           1040
#define IDC_EDIT_SLAVECOUNT             1041
#define IDC_EDIT_MASTERSTATE            1042
#define IDC_EDIT2                       1043
#define IDC_EDIT_PICKOFFSET_X           1044
#define IDC_EDIT_IN_ENT                 1045
#define IDC_BTN_CONN_SERVER             1046
#define IDC_EDIT_ORIGIN_Y               1047
#define IDC_EDIT_IN_SET                 1048
#define IDC_BTN_HOMING                  1049
#define IDC_EDIT_PICKOFFSET_Y           1050
#define IDC_EDIT_WORK_LOW               1051
#define IDC_BTN_FILE                    1052
#define IDC_EDIT_WORK_SET               1053
#define IDC_SIMUL_ON                    1054
#define IDC_EDIT_OUT_SET                1055
#define IDC_SIMUL_OFF                   1056
#define IDC_EDIT_WORK_OUT               1057
#define IDC_BTN_INIT                    1058
#define IDC_BTN_1D                      1059
#define IDC_BTN_CAL_CANCEL              1060
#define IDC_BTN_ESTOP                   1061
#define IDC_BTN_VISINIT                 1062
#define IDC_BTN_VISDEMO                 1063
#define IDC_BTN_READFILE                1064
#define IDC_BTN_STOPPER                 1065
#define IDC_BTN_INBELT                  1066
#define IDC_R1D_SIMULON                 1067
#define IDC_R1D_SIMULOFF                1068
#define IDC_BTN_1D_ONOFF                1069
#define IDC_BTN_HEADCAM_CAL             1070
#define IDC_RHDCAM_SIMULON              1071
#define IDC_RHDCAM_SIMULOFF             1072
#define IDC_BTN_HDCAM_ONOFF             1073
#define IDC_BTN_2D                      1074
#define IDC_R2D_SIMULON                 1075
#define IDC_R2D_SIMULOFF                1076
#define IDC_BTN_2D_ONOFF                1077
#define IDC_BTN_GETVISIONVERSION        1078
#define IDC_BTN_YPLUS                   1079
#define IDC_BTN_INSERTCHECK             1079
#define IDC_BTN_YMINUS                  1080
#define IDC_BTN_XMINUS                  1081
#define IDC_BTN_XPLUS                   1082
#define IDC_RCONTINUE                   1083
#define IDC_RRELATIVE                   1084
#define IDC_RJOG_HIGH                   1085
#define IDC_RJOG_MID                    1086
#define IDC_RJOG_LOW                    1087
#define IDC_STATIC_MODE                 1088
#define IDC_STATIC_SPEED                1089
#define IDC_BTN_LIVE                    1090
#define IDC_BTN_MARK                    1091
#define IDC_CB_TEACH                    1092
#define IDC_CHK_REPEAT                  1093
#define IDC_EDIT_REPEAT_DELAY           1094
#define IDC_EDIT_REPEAT_COUNT           1095
#define IDC_BTN_WORKBELT                1096
#define IDC_BTN_OUTBELT                 1097
#define IDC_BTN_PLATE                   1098
#define IDC_BTN_PLATE2                  1099
#define IDC_BTN_WIDTH                   1100
#define IDC_BUTTON1                     1101
#define IDC_BTN_WIDTH2                  1102
#define IDC_BTN_BLOW                    1102
#define IDC_BTN_2ND_XY                  1103
#define IDC_CB_SEL_CAMERA               1104
#define IDC_EDIT_LED1                   1105
#define IDC_EDIT_LED2                   1106
#define IDC_RADIO1                      1107
#define IDC_EDIT_LED3                   1108
#define IDC_RADIO11                     1108
#define IDC_RB_CAM2                     1109
#define IDC_RB_ZNO2                     1110
#define IDC_RADIO2                      1111
#define IDC_RADIO12                     1111
#define IDC_RADIO3                      1112
#define IDC_RADIO13                     1112
#define IDC_RADIO4                      1113
#define IDC_RADIO14                     1113
#define IDC_RADIO5                      1114
#define IDC_RADIO15                     1114
#define IDC_RADIO6                      1115
#define IDC_RADIO16                     1115
#define IDC_RADIO7                      1116
#define IDC_RADIO17                     1116
#define IDC_RADIO8                      1117
#define IDC_RADIO18                     1117
#define IDC_BTN_SERVO                   1118
#define IDC_RADIO19                     1118
#define IDC_BTN_SETCONVWIDTH            1119
#define IDC_RADIO20                     1119
#define IDC_RB_TARGET_HEAD2             1120
#define IDC_RADIO21                     1120
#define IDC_EDIT_CONVWIDTH              1121
#define IDC_RADIO22                     1121
#define IDC_BTN_UPDATE_CONV             1122
#define IDC_RADIO23                     1122
#define IDC_EDIT_CONVPUSHERZ            1123
#define IDC_RADIO24                     1123
#define IDC_RB_WAIT                     1124
#define IDC_RADIO25                     1124
#define IDC_BTN_SETCONVPUSHERZ          1125
#define IDC_RADIO26                     1125
#define IDC_RB_WAITPOSSET               1126
#define IDC_RADIO27                     1126
#define IDC_RB_WAITDELAYEDPOSSET        1127
#define IDC_RADIO28                     1127
#define IDC_BTN_TEACH_MINUS             1128
#define IDC_RADIO29                     1128
#define IDC_BTN_TEACH_PLUS              1129
#define IDC_CB_RATIO                    1130
#define IDC_EDIT_INPOS                  1131
#define IDC_BUTTON2                     1132
#define IDC_EDIT_INPOSMS                1133
#define IDC_BTN_CLEAR_POINT             1134
#define IDC_CHK_CATCH_MARK              1135
#define IDC_BTN_MOVEMCAL                1136
#define IDC_BUTTON3                     1137
#define IDC_BTN_SET_LIMIT               1137
#define IDC_BTN_GOPCBFIX                1138
#define IDC_BTN_PICKRECOG               1139
#define IDC_BTN_ANC_ZUP                 1139
#define IDC_BTN_SETHOMEZ                1140
#define IDC_BTN_HEAD_OFFSET             1141
#define IDC_BTN_MOVEMCALXY              1142
#define IDC_BTN_ANC_MOVE2               1142
#define IDC_BTN_ALIGN_OFFSET            1143
#define IDC_CHK_LOG1                    1144
#define IDC_BTN_SETHOMEX                1144
#define IDC_CHK_LOG2                    1145
#define IDC_BTN_SETSELFZ                1145
#define IDC_CHK_LOG3                    1146
#define IDC_BTN_ANC_MOVE3               1146
#define IDC_BTN_ANC_RELOADFILE          1146
#define IDC_CHK_LOG4                    1147
#define IDC_CHK_LOG5                    1148
#define IDC_CHK_LOG6                    1149
#define IDC_R2D_WMX3                    1150
#define IDC_R2D_SW                      1151
#define IDC_EDIT_FEED_X                 1152
#define IDC_EDIT_FEED_Y                 1153
#define IDC_CHK_INPUT_MOVE              1154
#define IDC_BTN_READXY                  1155
#define IDC_EDIT_VIS_X                  1156
#define IDC_EDIT_VIS_Y                  1157
#define IDC_EDIT_TORQUE_X               1158
#define IDC_EDIT_2D_X                   1159
#define IDC_EDIT_2D_Y                   1160
#define IDC_EDIT_2D_Y2                  1161
#define IDC_EDIT_1D_Y2                  1162
#define IDC_EDIT_CMD_X                  1163
#define IDC_EDIT_CMD_Y                  1164
#define IDC_BTN_MOVEMCALX               1165
#define IDC_EDIT_CATCH_DELAY            1166
#define IDC_EDIT_REPEAT_MARK            1167
#define IDC_CHECK_HOME_REPEAT           1168
#define IDC_EDIT_HOME_REPEAT_COUNT      1169
#define IDC_CHK_LOG0                    1170
#define IDC_CHECK_UPDATEINSERTOFFSET    1170
#define IDC_BTN_CONTROL                 1171
#define IDC_BTN_STOP                    1172
#define IDC_CHECK_ALIGN_REPEAT          1173
#define IDC_EDIT_ALIGN_REPEAT_COUNT     1174
#define IDC_CHK_LOG7                    1175
#define IDC_EDIT_HEADOFFSET_REPEAT_COUNT 1176
#define IDC_CHK_LOG_ALL                 1177
#define IDC_RADIO9                      1178
#define IDC_RADIO10                     1179
#define IDC_EDIT_CMD_R                  1180
#define IDC_EDIT_CMD_Z                  1181
#define IDC_EDIT_FEED_R                 1182
#define IDC_EDIT_FEED_Z                 1183
#define IDC_EDIT_TORQUE_R               1184
#define IDC_EDIT_TORQUE_Z               1185
#define IDC_EDIT_1ST_Y                  1186
#define IDC_EDIT_1ST_X                  1187
#define IDC_EDIT_2ND_X                  1188
#define IDC_EDIT_2ND_Y                  1189
#define IDC_EDIT_DIST_X                 1190
#define IDC_EDIT_DIST_Y                 1191
#define IDC_BTN_1ST_XY                  1192
#define IDC_RB_TARGET_OFFSET            1193
#define IDC_RB_TARGET_HEAD1             1194
#define IDC_BTN_CIRCLE_MARK             1195
#define IDC_CHK_LOG8                    1196
#define IDC_CHECK_HEADOFFSET_REPEAT     1197
#define IDC_BTN_PART                    1198
#define IDC_BTN_SETCONVPUSERZ_ORIGIN    1199
#define IDC_RB_ZNO1                     1200
#define IDC_BTN_CALC_CONVPUSERZ_ORIGIN2 1200
#define IDC_RB_ZNO3                     1201
#define IDC_RB_ZNO4                     1202
#define IDC_RB_ZNO5                     1203
#define IDC_RB_ZNO6                     1204
#define IDC_EDIT_HOME_Z                 1205
#define IDC_BTN_SETPCBFIX               1206
#define IDC_BTN_SETFDREF                1207
#define IDC_RB_FRONT                    1208
#define IDC_RB_REAR                     1209
#define IDC_BTN_SEND_CAMOFFSET          1210
#define IDC_BTN_GOFDREF                 1211
#define IDC_CHK_MULTI_RECOG             1212
#define IDC_RB_FANC                     1212
#define IDC_EDIT_ORIGIN_X               1213
#define IDC_RB_RANC                     1213
#define IDC_BTN_TEACH_ORIGIN            1214
#define IDC_BTN_ANC_TEACH1              1214
#define IDC_BTN_TEACH_MARK1             1215
#define IDC_BTN_ANC_TEACH2              1215
#define IDC_BTN_TEACH_MARK2             1216
#define IDC_BTN_ANC_APPLY               1216
#define IDC_EDIT_MARK_X1                1217
#define IDC_BTN_ANC_APPLY_Z             1217
#define IDC_EDIT_MARK_X2                1218
#define IDC_RB_ANCR0                    1218
#define IDC_EDIT_MARK_Y1                1219
#define IDC_RB_ANCR90                   1219
#define IDC_EDIT_MARK_Y2                1220
#define IDC_BTN_ANC_READFILE            1220
#define IDC_BTN_TEACH_NO1               1221
#define IDC_BTN_TEACH_NO2               1222
#define IDC_BTN_TEACH_NO3               1223
#define IDC_BTN_GO_ORIGIN               1224
#define IDC_BTN_GO_MARK1                1225
#define IDC_BTN_GO_MARK2                1226
#define IDC_BTN_GO_NO1                  1227
#define IDC_BTN_GO_NO2                  1228
#define IDC_BTN_GO_NO3                  1229
#define IDC_EDIT_NO_X1                  1230
#define IDC_EDIT_NO_Y1                  1231
#define IDC_EDIT_ROI_RATIO              1232
#define IDC_EDIT_NO_X2                  1233
#define IDC_EDIT_ROI_RATIO2             1234
#define IDC_EDIT_NO_Y2                  1235
#define IDC_EDIT_NO_X3                  1236
#define IDC_EDIT_NO_Y3                  1237
#define IDC_CHECK1                      1238
#define DC_BTN_MARK_TRAIN               1239
#define IDC_BTN_TEACH_NO4               1240
#define IDC_EDIT_PICK_R                 1241
#define IDC_EDIT_PICK_Z                 1242
#define IDC_CB_MACHINE_SPEED            1243
#define IDC_CB_SPEED_XY                 1244
#define IDC_BTN_GO_NO4                  1245
#define IDC_CB_SPEED_R                  1246
#define IDC_CB_SPEED_Z                  1247
#define IDC_EDIT_NO_X4                  1248
#define IDC_EDIT_PICK_DELAY             1249
#define IDC_CB_HEAD                     1250
#define IDC_BTN_GO_FEEDER               1251
#define IDC_BTN_TEACH_FEEDER            1252
#define IDC_CB_HEAD_NO1                 1253
#define IDC_BTN_SET_FEEDER              1254
#define IDC_EDIT_HM_DELAY               1254
#define IDC_CB_HEAD_NO2                 1255
#define IDC_CHK_BTN_ONLY_RECOG          1256
#define IDC_BTN_RUN                     1257
#define IDC_EDIT_NO_R1                  1258
#define IDC_EDIT_NO_Z1                  1259
#define IDC_EDIT_NO_R2                  1260
#define IDC_EDIT_NO_Z2                  1261
#define IDC_EDIT_NO_R3                  1262
#define IDC_EDIT_NO_Z3                  1263
#define IDC_CB_HEAD_NO3                 1264
#define IDC_EDIT_NO_Y4                  1265
#define IDC_EDIT_RES_X                  1266
#define IDC_EDIT_RES_Y                  1267
#define IDC_CHK_LOG9                    1268
#define IDC_EDIT_RES_R                  1269
#define IDC_BTN_SET_ALIGN_OFFSET        1270
#define IDC_CHK_LOG10                   1271
#define IDC_CHK_BTN_APPLY_VIS           1272
#define IDC_EDIT_NO_R4                  1273
#define IDC_BTN_SETCONVWIDTH_ORIGIN     1274
#define IDC_EDIT_NO_Z4                  1275
#define IDC_BTN_ZCOMPEN                 1276
#define IDC_CB_HEAD_NO4                 1277
#define IDC_BUTTON5                     1278
#define IDC_BTN_SETHOMER                1278
#define IDC_BTN_ZCOMPEN_ON              1279
#define IDC_RB_CAM1                     1280
#define IDC_BTN_MODULECAM_CAL           1281
#define IDC_RB_NO1                      1282
#define IDC_RB_NO2                      1283
#define IDC_BTN_ZMINUS                  1284
#define DC_BTN_RCCW                     1285
#define IDC_BTN_ZPLUS                   1286
#define DC_BTN_RCW                      1287
#define IDC_CHK_USE1D                   1288
#define IDC_CHK_USE2D                   1289
#define IDC_BTN_INIT_HEAD_OFFSET        1290
#define IDC_CHK_USEZCOMPEN              1291
#define IDC_BUTTON4                     1292
#define IDC_EDIT_PCB_THICKNESS          1293
#define IDC_EDIT_PCB_STANDBYZ_OFFSET    1294
#define IDC_BTN_SIMUL_STOPPERUP         1295
#define IDC_BTN_MANUAL                  1296
#define IDC_EDIT_LIMIT_MINUS            1297
#define IDC_EDIT_LIMIT_PLUS             1298
#define IDC_BTN_SUCTION                 1298
#define IDC_CHK_BTN_RETURN_FD           1299
#define IDC_EDIT_ANC_Z                  1299
#define IDC_BTN_RETURNTOFD              1300
#define IDC_EDIT_HOME_R                 1301
#define IDC_EDIT_PCB_THICKNESS2         1302
#define IDC_EDIT_HOME_X                 1302
#define IDC_EDIT_PCB_STANDBYZ_OFFSET2   1303
#define IDC_EDIT_LEVEL                  1304
#define IDC_BTN_AXISSERVO               1305
#define IDC_CHECK2                      1306
#define IDC_EDIT_COMPONENT_HEIGHT       1307
#define IDC_BTN_READJOBFILE             1308
#define IDC_CHK_SKIP_MOTORPOWER         1309
#define IDC_CHK_INIT_Y2_SHIFT           1310
#define IDC_BTN_TEACH_HM                1311
#define IDC_BTN_SAVE_HM                 1312
#define IDC_BTN_INIT_HEAD_REAROFFSET    1313
#define IDC_CHK_INFINITE                1314
#define IDC_CHK_LOG11                   1315
#define IDC_CHK_LOG12                   1316
#define IDC_CHK_LOG13                   1317
#define IDC_CHK_LOG14                   1318
#define IDC_CHK_LOG15                   1319
#define IDC_CHK_FIRSTPICKUP             1320
#define IDC_CHK_SKIP_VISION             1321
#define IDC_CHK_SIMUL_LOADING           1322
#define IDC_CHK_USE_PATH                1323
#define IDC_CHK_2STEP_Z                 1324
#define IDC_CHK_LOG16                   1325
#define IDC_CHK_USE_LOB                 1326
#define IDC_CHK_WORKEXISTSKIP           1327
#define IDC_BTN_R_OFFSET                1327
#define IDC_CHK_LOG17                   1328

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1329
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
